name: Deploy BcsFocus.API to Azure

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build BcsFocus.API
      run: dotnet build BcsFocus.API/BcsFocus.API.csproj --configuration Release

    - name: Deploy BcsFocus.API to Azure Web Apps
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'dev-bcsfocus-2'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'BcsFocus.API/bin/Release/net6.0/publish'
        slot-name: 'production'
