name: Deploy to Google Cloud

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: bcsfocus
        service_account_email: github@bcsfocus.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy
      uses: GoogleCloudPlatform/github-actions/deploy-appengine@master
      with:
        version: v1
